import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Inter} from "next/font/google";

const inter = Inter({subsets: ["latin"]});

const geistSans = Geist(
{
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono(
{
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata =
{
  title: "Online Calculator",
  description: "Generated by create next app",
};

export default function RootLayout(
{
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Boldonse&display=swap" rel="stylesheet"/>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
